### ISSUE TITLE
'Object doesn't support property or method 'config'' error in IE

### ISSUE THREAD

**Issue by ghost** [MitocGroup/deep-microservices-root-angular1#105]
See attached: empty page is displayed in IE and `Object doesn't support property or method 'config' error` is in console.
![screenshot from 2016-11-01 09 49 36](https://cloud.githubusercontent.com/assets/10956412/19885170/e653a3d8-a025-11e6-9f8f-df54da931dd7.png)

**Comment by AScripnic** [comment]
https://github.com/MitocGroup/deep-framework/issues/471

**Comment by eistrati** [comment]
Verified.
